@startuml

title __OBSERVER's Class Diagram__\n

  namespace at.omi.blatt6.a4.sensor.example.observer {
    interface at.omi.blatt6.a4.sensor.example.observer.IObservable {
        {abstract} + add()
        {abstract} + notifyObserver()
        {abstract} + remove()
    }
  }
  

  namespace at.omi.blatt6.a4.sensor.example.observer {
    interface at.omi.blatt6.a4.sensor.example.observer.IObserver {
        {abstract} + update()
    }
  }
  

  namespace at.omi.blatt6.a4.sensor.example.observer {
    class at.omi.blatt6.a4.sensor.example.observer.SomeSensor {
        - allObservers : ArrayList<IObserver>
        - currentValue : long
        + SomeSensor()
        + add()
        + getCurrentValue()
        + notifyObserver()
        + remove()
        - setCurrentValue()
    }
  }
  

  namespace at.omi.blatt6.a4.sensor.example.observer {
    class at.omi.blatt6.a4.sensor.example.observer.SomeSensor.ValueGenerator {
        + run()
    }
  }
  

  namespace at.omi.blatt6.a4.sensor.example.observer {
    class at.omi.blatt6.a4.sensor.example.observer.SomeSensorReader {
        + SomeSensorReader()
        + update()
    }
  }
  

  namespace at.omi.blatt6.a4.sensor.example.observer {
    class at.omi.blatt6.a4.sensor.example.observer.Test {
        {static} + main()
    }
  }
  

  at.omi.blatt6.a4.sensor.example.observer.SomeSensor .up.|> at.omi.blatt6.a4.sensor.example.observer.IObservable
  at.omi.blatt6.a4.sensor.example.observer.SomeSensor +-down- at.omi.blatt6.a4.sensor.example.observer.SomeSensor.ValueGenerator
  at.omi.blatt6.a4.sensor.example.observer.SomeSensor.ValueGenerator .up.|> java.lang.Runnable
  at.omi.blatt6.a4.sensor.example.observer.SomeSensorReader .up.|> at.omi.blatt6.a4.sensor.example.observer.IObserver
  at.omi.blatt6.a4.sensor.example.observer.SomeSensorReader o-- at.omi.blatt6.a4.sensor.example.observer.SomeSensor : sensor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
